// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiaqmkIPkUgQCsH77OXTGINdiZieSQKQ',
    appId: '1:44397234167:web:8f56aa92f55b0bf43250f2',
    messagingSenderId: '44397234167',
    projectId: 'coba-80a69',
    authDomain: 'coba-80a69.firebaseapp.com',
    storageBucket: 'coba-80a69.appspot.com',
    measurementId: 'G-3541LLWEMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1n5H3tI7d_4b6J0qb5rCmiZQ4POky7H0',
    appId: '1:44397234167:android:ccd319ef05819da83250f2',
    messagingSenderId: '44397234167',
    projectId: 'coba-80a69',
    storageBucket: 'coba-80a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaU67nHzTF8IDdgyEQyRf_Ru58z2OCPfI',
    appId: '1:44397234167:ios:cf0bd842911e43663250f2',
    messagingSenderId: '44397234167',
    projectId: 'coba-80a69',
    storageBucket: 'coba-80a69.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaU67nHzTF8IDdgyEQyRf_Ru58z2OCPfI',
    appId: '1:44397234167:ios:4f1c29d4e0b6c1a33250f2',
    messagingSenderId: '44397234167',
    projectId: 'coba-80a69',
    storageBucket: 'coba-80a69.appspot.com',
    iosBundleId: 'com.example.authFirebase.RunnerTests',
  );
}