// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPgzFuNlNnbpnTF73hU3LcVK8L74n7d6w',
    appId: '1:144705129084:web:52882bacd838b2bfae57f9',
    messagingSenderId: '144705129084',
    projectId: 'mobile-firebase-61857',
    authDomain: 'mobile-firebase-61857.firebaseapp.com',
    storageBucket: 'mobile-firebase-61857.appspot.com',
    measurementId: 'G-CJ7VH97C38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeMJhkWWXNcLhgQnD82nGhZ8G5ustfKFA',
    appId: '1:144705129084:android:90629beb9a883bacae57f9',
    messagingSenderId: '144705129084',
    projectId: 'mobile-firebase-61857',
    storageBucket: 'mobile-firebase-61857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgN30O98lqW_6OEOX7PzkXpK7LUg8I2N4',
    appId: '1:144705129084:ios:23f160ea1a1520b4ae57f9',
    messagingSenderId: '144705129084',
    projectId: 'mobile-firebase-61857',
    storageBucket: 'mobile-firebase-61857.appspot.com',
    iosBundleId: 'com.example.flutterUtsmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgN30O98lqW_6OEOX7PzkXpK7LUg8I2N4',
    appId: '1:144705129084:ios:9591acbec7dd209aae57f9',
    messagingSenderId: '144705129084',
    projectId: 'mobile-firebase-61857',
    storageBucket: 'mobile-firebase-61857.appspot.com',
    iosBundleId: 'com.example.flutterUtsmobile.RunnerTests',
  );
}
